nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.185.238.42

jupyterhub:
  prePuller:
    continuous:
      # Same image as datahub, so no continouus pre-puller needed
      enabled: false
  cull:
    # Cull after 30min of inactivity
    every: 300
    timeout: 1800
    # No pods over 12h long, no workshop is gonna be more than that :)
    maxAge: 43200
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2023-12-21
  hub:
    # No more than 200 users at any given time
    activeServerLimit: 200
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2023-12-21
    config:
      JupyterHub:
        admin_access: false
        authenticator_class: dummy
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2023-12-21
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2023-12-21
  singleuser:
    extraEnv:
      # Unset NotebookApp from hub/values. Necessary for recent lab versions.
      JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    nodeSelector:
      # Co-locate with datahub, since workshop shares its image
      hub.jupyter.org/pool-name: datahub-pool
    image: {}
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      # As low a guarantee as possible
      guarantee: 128M
      limit: 1G
  custom:
    group_profiles:
      # DataHub Infrastructure staff
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        admin: true
      # Demog Data Event, April 1 - Sep 30, https://github.com/berkeley-dsep-infra/datahub/issues/5643
      course::1534506::enrollment_type::teacher:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/demog-dataevent-readwrite
            subPath: _shared/course/demog-dataevent
      course::1534506::enrollment_type::ta:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/demog-dataevent-readwrite
            subPath: _shared/course/demog-dataevent
      course::1534506::enrollment_type::student:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/demog-dataevent
            subPath: _shared/course/demog-dataevent
            readOnly: true
      course::1534506: #Demog Data Event, April 1 - Sep 30, https://github.com/berkeley-dsep-infra/datahub/issues/5643
        mem_limit: 4096M
        mem_guarantee: 4096M