nfsPVC:
  nfs:
    shareName: shares/ugr01/staging

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - ugr01-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - ugr01-staging.datahub.berkeley.edu
