nfsPVC:
  nfs:
    shareName: shares/datahub/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - prod.datahub.berkeley.edu
      - datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - prod.datahub.berkeley.edu
          - datahub.berkeley.edu
  proxy:
    https:
      enabled: false
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 80Gi
    resources:
      requests:
        # DataHub often takes up a full CPU now, so let's guarantee it at least that
        cpu: 1
        memory: 1Gi
      limits:
        memory: 2Gi
  scheduling:
    userPlaceholder:
      enabled: false
