name: Deploy images to hubs

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check out the image repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --force-reinstall git+https://github.com/shaneknapp/hubploy.git@major-refactor

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
        files_ignore: |
            .github/**
            images/**